### PR TITLE
OSA updates.

### PR DESCRIPTION
**Pull request by armaan**
These changes are required to make OSA work.

### CODE REVIEW

**Comment by fghaas** [comment]
Most of these look fine to me. I do have a couple of nits to pick that I added line notes for.

**Comment by fghaas** [comment]
OK @armaan, is this ready to test now? Should this template be suitable for deploying OpenStack with no further manual modifications? Would connectivity from VMs to the outside be expected to work?

**Comment by armaan** [comment]
@fghaas , Yes it is ready for test, you will face one bug[1], you have to fix this manually. No,sorry, connectivity from VMs to the outside will not work.

[1]  https://bugs.launchpad.net/openstack-ansible/+bug/1545505

**Comment by fghaas** [comment]
Well what do we do about outside connectivity then?

**Pull request merged**
